<a href="https://colab.research.google.com/github/chettkulkarni/deep_learning/blob/master/ungraded%204/Chapter_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor Fundamentals

In [0]:
import torch

In [0]:
a = torch.ones(3,3)

In [0]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
a = torch.ones(2,3)

In [0]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
a = torch.empty(2,4)

In [0]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
a[1] = 3

In [0]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
a


tensor([[2.2639e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.0000e+00, 3.0000e+00, 3.0000e+00, 3.0000e+00]])

In [0]:
b = torch.ones(2,4)

In [0]:
a + b

tensor([[1., 1., 1., 1.],
        [4., 4., 4., 4.]])

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])

In [0]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points.shape

torch.Size([3, 2])

Access Elements

In [0]:
points[0, 1]

tensor(4.)

In [0]:
points[0]

tensor([1., 4.])

###Size, storage offset, and strides

Access Storage of Tensors

In [0]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

Index storage Manually

In [0]:
points_storage = points.storage()
points_storage[0]

1.0

In [0]:
points.storage()[1]

4.0

In [0]:
points.storage()[0]

1.0

Get the second point in the tensor

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])

In [0]:
points[1]

tensor([2., 1.])

In [0]:
second_point = points[1]
second_point.storage_offset()

2

In [0]:
second_point.size()

torch.Size([2])

Stride

In [0]:
points.stride()

(2, 1)

In [0]:
second_point.storage_offset()

2

In [0]:
second_point.stride()

(1,)

Changing Subtensor affects the Original tensors too

In [0]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
second_point

tensor([2., 1.])

In [0]:
second_point[0] = 10.0

In [0]:
second_point

tensor([10.,  1.])

In [0]:
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

Clone Subtensor, so as not to change Original Tensor

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

##Transpose

In [0]:
points_t = points.t()

In [0]:
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

Points and Points Transpose share the Storage

In [0]:
id(points.storage()) == id(points_t.storage())

True

Points and Points Transpose differe in shape and Stride

In [0]:
points.stride()

(2, 1)

In [0]:
points_t.stride()

(1, 2)

In [0]:
points.shape

torch.Size([3, 2])

In [0]:
points_t.shape

torch.Size([2, 3])

#Numerical Types

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [0]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [0]:
double_points.dtype

torch.float64

In [0]:
short_points.dtype

torch.int16

Cast dtypes

In [0]:
double_points = torch.zeros(10, 2).double()

In [0]:
double_points.dtype

torch.float64

##NumPy interoperability

In [0]:
points = torch.ones(3, 4)

In [0]:
points_np = points.numpy()

In [0]:
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

PyTorch tensor from a NumPy array

In [0]:
points = torch.from_numpy(points_np)

In [0]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating Tensors on GPU

In [0]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]],
device='cuda')

OR can use below code to create Tensors on GPU

In [0]:
points_gpu = points.to(device='cuda')